# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

# This action will automatically create a pull request against master if the pushed branch
# has a branch path spec like beta/pipelinebuild/*. Configure this action by updating the
# environment variable values[0]. 

name: autoGenPR

# Controls when the action will run. Triggers the workflow on push
# events but only for branches with the following branch spec: "beta/pipelinebuild/*"
on:
  push:
    branches:
      - "test/*"
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "create-pull-request"
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - name: Get Version
      id: GetVersion
      run: .\scripts\getLatestVersion.ps1
      shell: pwsh    

    - name: Create PR using the GitHub REST API via hub
      shell: bash
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        MESSAGE_TITLE: "release ${{ steps.GetVersion.outputs.tag }}"
        MESSAGE_BODY: "This pull request was automatically created by the GitHub Action, **${{github.workflow}}**. \n\n The commit hash is _${{github.sha}}_. \n\n **Important** Check for unexpected deletions or changes in this PR."
        REVIEWERS: ramsessanchez
        ASSIGNEDTO: ramsessanchez
        LABELS: generated
        BASE: main
      run: |
        curl -fsSL https://github.com/github/hub/raw/master/script/get | bash -s 2.14.1
        bin/hub pull-request -b "$BASE" -h "$GITHUB_REF" -m "$MESSAGE_TITLE" -m "$MESSAGE_BODY" -r "$REVIEWERS" -a "$ASSIGNEDTO" -l "$LABELS"


