name: Git Release

on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:
  
jobs:
  create_a:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - run: mkdir -p path/to/artifact
      - run: echo hello > path/to/artifact/world.txt
      - uses: actions/upload-artifact@v2
        with:
          name: drop2
          path: path/to/artifact/world.txt      
      
  Git_Release:
    needs: create_a
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Dowload this Artifact
        uses: actions/download-artifact@v2
        with:
          name: drop2
          PATH: drop2
      - name: Display structure of downloaded files
        run: ls -R
    
      - name: Download workflow artifact
        uses: dawidd6/action-download-artifact@v2.14.1
        with: 
           workflow: test-upload.yml
           workflow_conclusion: success
           branch: main
           event: push
           name: drop 
           path: drop
      - name: Github Release
        uses: anton-yurchenko/git-release@v4.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
          DRAFT_RELEASE: "false"
          PRE_RELEASE: "false"
          CHANGELOG_FILE: "CHANGELOG.md"
          ALLOW_EMPTY_CHANGELOG: "true"
        with:
          args: |
              drop2/world.txt
