# This is a basic workflow to help you get started with Actions

name: Pr Test
on:
  pull_request:
    branches: 
      - "test/*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Changelog CI
        uses: saadmk11/changelog-ci@v0.8.0
          
