name: CI
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    environment: test
    runs-on: ubuntu-latest
    env: 
      TAG: v1.1.5
    steps: 
    - uses: actions/checkout@v2

    - run: mkdir -p path/to/artifact

    - run: echo hello > path/to/artifact/world.txt

    - uses: actions/upload-artifact@v2
      with:
        name: drop
        path: path/to/artifact/**
    - name: Create tag
      uses: rickstaa/action-create-tag@v1.2.0
      with:
        tag: ${{ env.TAG }}
    - name: Queue Git Release
      uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: Git Release
        token: ${{ secrets.PERSONAL_TOKEN }}
        ref: ${{ env.TAG }}

