# This is a basic workflow to help you get started with Actions

name: Triggered on PR
on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  create-artifact1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: write lines 
        run: | 
          mkdir -p artifact
          echo hello > artifact/hello.txt
          echo world > artifact/world.txt
      - name: upload artifact 
        uses: actions/upload-artifact@v2
        with:
          name: drop
          path: artifact/

  create-artifact2:
    needs: create-artifact1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: write lines 
        run: | 
          mkdir -p artifact2
          echo hello > artifact2/hello.txt
          echo world! > artifact2/world.txt
      - name: upload artifact 
        uses: actions/upload-artifact@v2
        with:
          name: drop2
          path: artifact2/
  
  compare-artifacts:
    needs: create-artifact2
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2.2.2

      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.0.10
        with: 
          path: drop-artifacts/
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: drop-artifacts/

      - name: test file compare 
        run: python ./scripts/compare-files.py drop-artifacts/drop/ drop-artifacts/drop2/

      
      

  
    
